# HTTP Server
server:
  port: 9999

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eaq19/SpringCloudConfig-GitRepository
          password: 
          username: 
